//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jieba.Net.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jieba.Net.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;\u8000&quot;: [
        ///    &quot;E-v&quot;,
        ///    &quot;M-nr&quot;,
        ///    &quot;E-nr&quot;,
        ///    &quot;B-a&quot;,
        ///    &quot;S-v&quot;,
        ///    &quot;E-a&quot;,
        ///    &quot;M-nt&quot;,
        ///    &quot;B-i&quot;,
        ///    &quot;B-n&quot;,
        ///    &quot;B-ns&quot;,
        ///    &quot;B-nz&quot;,
        ///    &quot;E-n&quot;,
        ///    &quot;M-i&quot;,
        ///    &quot;S-vg&quot;,
        ///    &quot;M-nrfg&quot;,
        ///    &quot;M-n&quot;,
        ///    &quot;E-nrfg&quot;
        ///  ],
        ///  &quot;\u6d89&quot;: [
        ///    &quot;B-v&quot;,
        ///    &quot;E-v&quot;,
        ///    &quot;S-vg&quot;,
        ///    &quot;B-vn&quot;,
        ///    &quot;B-n&quot;,
        ///    &quot;M-n&quot;,
        ///    &quot;E-i&quot;,
        ///    &quot;M-l&quot;,
        ///    &quot;M-i&quot;,
        ///    &quot;E-nr&quot;,
        ///    &quot;M-nr&quot;,
        ///    &quot;E-vn&quot;,
        ///    &quot;B-ns&quot;,
        ///    &quot;E-l&quot;,
        ///    &quot;S-j&quot;,
        ///    &quot;B-i&quot;
        ///  ],
        ///  &quot;\u8c08&quot;: [
        ///    &quot;S-v&quot;,
        ///    &quot;B-vn&quot;,
        ///    &quot;B-v&quot;,
        ///    [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string char_state_tab {
            get {
                return ResourceManager.GetString("char_state_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AT&amp;T 3 nz
        ///B超 3 n
        ///c# 3 nz
        ///C# 3 nz
        ///c++ 3 nz
        ///C++ 3 nz
        ///T恤 4 n
        ///A座 3 n
        ///A股 3 n
        ///A型 3 n
        ///A轮 3 n
        ///AA制 3 n
        ///AB型 3 n
        ///B座 3 n
        ///B股 3 n
        ///B型 3 n
        ///B超 3 n
        ///B轮 3 n
        ///BB机 3 n
        ///BP机 3 n
        ///C盘 3 n
        ///C座 3 n
        ///C语言 3 n
        ///CD盒 3 n
        ///CD机 3 n
        ///CALL机 3 n
        ///D盘 3 n
        ///D座 3 n
        ///D版 3 n
        ///E盘 3 n
        ///E座 3 n
        ///E化 3 n
        ///E通 3 n
        ///F盘 3 n
        ///F座 3 n
        ///G盘 3 n
        ///H盘 3 n
        ///H股 3 n
        ///I盘 3 n
        ///IC卡 3 n
        ///IP卡 3 n
        ///IP电话 3 n
        ///IP地址 3 n
        ///K党 3 n
        ///K歌之王 3 n
        ///N年 3 n
        ///O型 3 n
        ///PC机 3 n
        ///PH值 3 n
        ///SIM卡 3 n
        ///U盘 3 n
        ///VISA卡 3 n
        ///Z盘 3 n
        ///Q版 3 n
        ///QQ号 3 n
        ///RSS订阅 3 n
        ///T盘 3 n
        ///X光 3 n
        ///X光线 3 n
        ///X [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string dict {
            get {
                return ResourceManager.GetString("dict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;E-e&quot;: {
        ///    &quot;\u5440&quot;: -0.65302718677052,
        ///    &quot;\u54c8&quot;: -2.5026062268874014,
        ///    &quot;\u9957&quot;: -4.918520005188451,
        ///    &quot;\u4f19&quot;: -2.864396271492904,
        ///    &quot;\u54df&quot;: -1.3746663231247713,
        ///    &quot;\u585e&quot;: -6.52795791762255,
        ///    &quot;\u5925&quot;: -2.864396271492904,
        ///    &quot;\u98e8&quot;: -4.918520005188451,
        ///    &quot;\u55b2&quot;: -1.3746663231247713,
        ///    &quot;\u563b&quot;: -6.52795791762255,
        ///    &quot;\u547c&quot;: -2.5576660040704287
        ///  },
        ///  &quot;E-d&quot;: {
        ///    &quot;\u7981&quot;: -6.305212599605907,
        ///    &quot;\u6000&quot;: -10.801931077366499,
        ///    &quot;\u8702&quot;: -9.443807 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string pos_prob_emit {
            get {
                return ResourceManager.GetString("pos_prob_emit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;E-e&quot;: -3.14e+100,
        ///  &quot;E-d&quot;: -3.14e+100,
        ///  &quot;E-g&quot;: -3.14e+100,
        ///  &quot;E-f&quot;: -3.14e+100,
        ///  &quot;E-a&quot;: -3.14e+100,
        ///  &quot;E-c&quot;: -3.14e+100,
        ///  &quot;E-b&quot;: -3.14e+100,
        ///  &quot;E-m&quot;: -3.14e+100,
        ///  &quot;S-rg&quot;: -10.275268591948773,
        ///  &quot;E-o&quot;: -3.14e+100,
        ///  &quot;E-n&quot;: -3.14e+100,
        ///  &quot;E-i&quot;: -3.14e+100,
        ///  &quot;E-h&quot;: -3.14e+100,
        ///  &quot;E-k&quot;: -3.14e+100,
        ///  &quot;E-j&quot;: -3.14e+100,
        ///  &quot;E-u&quot;: -3.14e+100,
        ///  &quot;E-t&quot;: -3.14e+100,
        ///  &quot;E-w&quot;: -3.14e+100,
        ///  &quot;E-v&quot;: -3.14e+100,
        ///  &quot;E-q&quot;: -3.14e+100,
        ///  &quot;E-p&quot;: -3.14e+100,
        ///  &quot;E-s&quot;: -3.14e+100,
        ///  &quot;M-bg&quot;: -3.14 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string pos_prob_start {
            get {
                return ResourceManager.GetString("pos_prob_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;E-e&quot;: {
        ///    &quot;S-nr&quot;: -4.3010575721402144,
        ///    &quot;S-ng&quot;: -4.3010575721402144,
        ///    &quot;B-rz&quot;: -6.498282149476434,
        ///    &quot;B-mq&quot;: -6.498282149476434,
        ///    &quot;S-ul&quot;: -4.418840607796598,
        ///    &quot;S-vg&quot;: -4.552372000421121,
        ///    &quot;S-y&quot;: -3.5538431703099933,
        ///    &quot;S-v&quot;: -2.4378391389300145,
        ///    &quot;S-u&quot;: -5.111987788356543,
        ///    &quot;S-r&quot;: -1.4678442280839983,
        ///    &quot;S-q&quot;: -5.805134968916488,
        ///    &quot;B-vn&quot;: -6.498282149476434,
        ///    &quot;S-n&quot;: -3.7256934272366524,
        ///    &quot;S-m&quot;: -3.9333327920148973,
        ///    &quot;S-j&quot;: -4.3010575721402144,
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string pos_prob_trans {
            get {
                return ResourceManager.GetString("pos_prob_trans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;M&quot;: {
        ///    &quot;\u8000&quot;: -8.476516761725026,
        ///    &quot;\u8604&quot;: -14.3722960586986,
        ///    &quot;\u6d89&quot;: -10.560093388552664,
        ///    &quot;\u8c08&quot;: -8.34522308412325,
        ///    &quot;\u4f0a&quot;: -8.021846737364996,
        ///    &quot;\u9810&quot;: -10.938308854213453,
        ///    &quot;\u6d1e&quot;: -9.547990342793838,
        ///    &quot;\u54a3&quot;: -15.065443239258546,
        ///    &quot;\u7322&quot;: -12.868218661922326,
        ///    &quot;\u5aa7&quot;: -13.812680270763178,
        ///    &quot;\u7926&quot;: -8.994705511256056,
        ///    &quot;\u9da9&quot;: -13.812680270763178,
        ///    &quot;\u7f2a&quot;: -11.751257234586019,
        ///    &quot;\u6cb3&quot;: -7.144452022345774,
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string prob_emit {
            get {
                return ResourceManager.GetString("prob_emit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;M&quot;: {
        ///    &quot;M&quot;: -1.2603623820268226,
        ///    &quot;E&quot;: -0.33344856811948514
        ///  },
        ///  &quot;S&quot;: {
        ///    &quot;S&quot;: -0.6658631448798212,
        ///    &quot;B&quot;: -0.7211965654669841
        ///  },
        ///  &quot;B&quot;: {
        ///    &quot;M&quot;: -0.916290731874155,
        ///    &quot;E&quot;: -0.51082562376599
        ///  },
        ///  &quot;E&quot;: {
        ///    &quot;S&quot;: -0.8085250474669937,
        ///    &quot;B&quot;: -0.5897149736854513
        ///  }
        ///} 的本地化字符串。
        /// </summary>
        public static string prob_trans {
            get {
                return ResourceManager.GetString("prob_trans", resourceCulture);
            }
        }
    }
}
